"""editing models 

Revision ID: 1faa86a59ad9
Revises: 95ce69f27904
Create Date: 2026-04-11 17:26:17.919105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1faa86a59ad9'
down_revision: Union[str, Sequence[str], None] = '95ce69f27904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('sportmonks_country_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'league', ['sportmonks_country_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league', type_='unique')
    op.drop_column('league', 'sportmonks_country_id')
    # ### end Alembic commands ###
