"""add_continent_to_country

Revision ID: 2db98b0bb504
Revises: f97dd8edd962
Create Date: 2026-04-11 16:43:33.601089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db98b0bb504'
down_revision: Union[str, Sequence[str], None] = 'f97dd8edd962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('continent_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'continent_id')
    # ### end Alembic commands ###
