"""editing models 

Revision ID: 441dd06db0e7
Revises: 1faa86a59ad9
Create Date: 2026-04-11 17:37:57.107180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441dd06db0e7'
down_revision: Union[str, Sequence[str], None] = '1faa86a59ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('league_sportmonks_country_id_key'), 'league', type_='unique')
    op.drop_column('league', 'sportmonks_country_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('sportmonks_country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('league_sportmonks_country_id_key'), 'league', ['sportmonks_country_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
