"""editing models 

Revision ID: 5f85d5f9b7ae
Revises: 441dd06db0e7
Create Date: 2026-04-19 15:24:33.596447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f85d5f9b7ae'
down_revision: Union[str, Sequence[str], None] = '441dd06db0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'country_code')
    op.drop_column('country', 'full_name')
    op.drop_column('team', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('country_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('country', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('country', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
