"""upgrading parser

Revision ID: 76f0d3dcf7d5
Revises: 5f85d5f9b7ae
Create Date: 2026-04-27 14:10:33.065234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f0d3dcf7d5'
down_revision: Union[str, Sequence[str], None] = '5f85d5f9b7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE position CASCADE")
    op.add_column('player', sa.Column('position_name', sa.String(), nullable=False))
    op.add_column('player', sa.Column('detailed_position', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('player_position_id_fkey'), 'player', 'position', ['position_id'], ['id'])
    op.drop_column('player', 'detailed_position')
    op.drop_column('player', 'position_name')
    op.create_table('position',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('position_pkey'))
    )
    # ### end Alembic commands ###
