"""editing models 

Revision ID: 95ce69f27904
Revises: 2db98b0bb504
Create Date: 2026-04-11 17:08:01.675602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ce69f27904'
down_revision: Union[str, Sequence[str], None] = '2db98b0bb504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('country', 'continent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('continent', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('country', 'full_name')
    # ### end Alembic commands ###
