"""create_all_tablesv3

Revision ID: a92de80f8748
Revises: e79e2e691cd8
Create Date: 2026-04-10 14:02:51.242366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92de80f8748'
down_revision: Union[str, Sequence[str], None] = 'e79e2e691cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('sportmonks_country_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('country_sportmonks_id_key'), 'country', type_='unique')
    op.create_unique_constraint(None, 'country', ['sportmonks_country_id'])
    op.drop_column('country', 'sportmonks_id')
    op.add_column('league', sa.Column('sportmonks_league_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'league', ['sportmonks_league_id'])
    op.add_column('player', sa.Column('sportmonks_player_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'player', ['sportmonks_player_id'])
    op.add_column('team', sa.Column('sportmonks_team_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'team', ['sportmonks_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_column('team', 'sportmonks_team_id')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'sportmonks_player_id')
    op.drop_constraint(None, 'league', type_='unique')
    op.drop_column('league', 'sportmonks_league_id')
    op.add_column('country', sa.Column('sportmonks_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'country', type_='unique')
    op.create_unique_constraint(op.f('country_sportmonks_id_key'), 'country', ['sportmonks_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('country', 'sportmonks_country_id')
    # ### end Alembic commands ###
