"""create_all_tablesv2

Revision ID: e79e2e691cd8
Revises: a82a2c148275
Create Date: 2026-04-10 13:23:59.978138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79e2e691cd8'
down_revision: Union[str, Sequence[str], None] = 'a82a2c148275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('sportmonks_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'country', ['sportmonks_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_column('country', 'sportmonks_id')
    # ### end Alembic commands ###
