"""editing model player nullable country id

Revision ID: efa7f500347a
Revises: f66fa6a7c9ff
Create Date: 2026-05-20 01:14:08.993040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa7f500347a'
down_revision: Union[str, Sequence[str], None] = 'f66fa6a7c9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
