"""upgrading parser

Revision ID: f66fa6a7c9ff
Revises: 76f0d3dcf7d5
Create Date: 2026-04-27 14:42:11.585620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66fa6a7c9ff'
down_revision: Union[str, Sequence[str], None] = '76f0d3dcf7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
